### ISSUE TITLE
Deploy fails, 'connection refused'

### ISSUE THREAD

**Issue by yaronr** [wurstmeister/storm-docker#3]
Hi

I'm using boot2docker.
fig up.
Storm UI working @ http://192.168.59.103:49080/
I tried:
storm jar target/my.jar my.poackage.Topology my-topology -c nimbus.host=192.168.59.103
--> connection refused
storm jar target/my.jar my.poackage.Topology my-topology -c nimbus.host=192.168.59.103:49627
--> UnknownHostException
storm jar target/my.jar my.poackage.Topology my-topology 192.168.59.103
--> Connection refused

I'm obviously doing something wrong, but what?  :-)

PS I looked at: https://github.com/wurstmeister/storm-kafka-0.8-plus-test
I don't understand what you mean by <KafraZookeeper> - and how it relates to the default storm-docker (without kafka). Is it the IP:port of the zookeeper?

I must say I checked the storm documentation as well:
http://storm.incubator.apache.org/documentation/Command-line-client.html
which just states : Syntax: storm jar topology-jar-path class ...
without explaining what '...' includes

Thank you very much for your patience.

**Comment by Ali-Alhaboby** [comment]
Problem with Apache Storm : connection refused
I'm facing this problem when I have installed Apache Storm on two machines on AWS EC2 Amazon
 storm list 
Running: java -client -Dstorm.options=nimbus.host%3D172.31.32.97,nimbus.thrift.port%3D6627 -Dstorm.home=/usr/local/src/apache-storm-0.9.4 -Dstorm.log.dir=/usr/local/src/apache-storm-0.9.4/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /usr/local/src/apache-storm-0.9.4/lib/commons-codec-1.6.jar:/usr/local/src/apache-storm-0.9.4/lib/json-simple-1.1.jar:/usr/local/src/apache-storm-0.9.4/lib/storm-core-0.9.4.jar:/usr/local/src/apache-storm-0.9.4/lib/log4j-over-slf4j-1.6.6.jar:/usr/local/src/apache-storm-0.9.4/lib/hiccup-0.3.6.jar:/usr/local/src/apache-storm-0.9.4/lib/carbonite-1.4.0.jar:/usr/local/src/apache-storm-0.9.4/lib/tools.macro-0.1.0.jar:/usr/local/src/apache-storm-0.9.4/lib/ring-servlet-0.3.11.jar:/usr/local/src/apache-storm-0.9.4/lib/commons-logging-1.1.3.jar:/usr/local/src/apache-storm-0.9.4/lib/servlet-api-2.5.jar:/usr/local/src/apache-storm-0.9.4/lib/joda-time-2.0.jar:/usr/local/src/apache-storm-0.9.4/lib/commons-lang-2.5.jar:/usr/local/src/apache-storm-0.9.4/lib/asm-4.0.jar:/usr/local/src/apache-storm-0.9.4/lib/disruptor-2.10.1.jar:/usr/local/src/apache-storm-0.9.4/lib/jetty-util-6.1.26.jar:/usr/local/src/apache-storm-0.9.4/lib/clj-stacktrace-0.2.2.jar:/usr/local/src/apache-storm-0.9.4/lib/tools.cli-0.2.4.jar:/usr/local/src/apache-storm-0.9.4/lib/math.numeric-tower-0.0.1.jar:/usr/local/src/apache-storm-0.9.4/lib/ring-devel-0.3.11.jar:/usr/local/src/apache-storm-0.9.4/lib/reflectasm-1.07-shaded.jar:/usr/local/src/apache-storm-0.9.4/lib/ring-jetty-adapter-0.3.11.jar:/usr/local/src/apache-storm-0.9.4/lib/ring-core-1.1.5.jar:/usr/local/src/apache-storm-0.9.4/lib/commons-exec-1.1.jar:/usr/local/src/apache-storm-0.9.4/lib/kryo-2.21.jar:/usr/local/src/apache-storm-0.9.4/lib/logback-core-1.0.13.jar:/usr/local/src/apache-storm-0.9.4/lib/logback-classic-1.0.13.jar:/usr/local/src/apache-storm-0.9.4/lib/commons-fileupload-1.2.1.jar:/usr/local/src/apache-storm-0.9.4/lib/clojure-1.5.1.jar:/usr/local/src/apache-storm-0.9.4/lib/jline-2.11.jar:/usr/local/src/apache-storm-0.9.4/lib/chill-java-0.3.5.jar:/usr/local/src/apache-storm-0.9.4/lib/clout-1.0.1.jar:/usr/local/src/apache-storm-0.9.4/lib/clj-time-0.4.1.jar:/usr/local/src/apache-storm-0.9.4/lib/objenesis-1.2.jar:/usr/local/src/apache-storm-0.9.4/lib/compojure-1.1.3.jar:/usr/local/src/apache-storm-0.9.4/lib/snakeyaml-1.11.jar:/usr/local/src/apache-storm-0.9.4/lib/minlog-1.2.jar:/usr/local/src/apache-storm-0.9.4/lib/commons-io-2.4.jar:/usr/local/src/apache-storm-0.9.4/lib/jgrapht-core-0.9.0.jar:/usr/local/src/apache-storm-0.9.4/lib/jetty-6.1.26.jar:/usr/local/src/apache-storm-0.9.4/lib/core.incubator-0.1.0.jar:/usr/local/src/apache-storm-0.9.4/lib/slf4j-api-1.7.5.jar:/usr/local/src/apache-storm-0.9.4/lib/tools.logging-0.2.3.jar:/usr/local/src/apache-storm-0.9.4/conf:/usr/local/src/apache-storm-0.9.4/bin backtype.storm.command.list
53149 [main] INFO  backtype.storm.thrift - Connecting to Nimbus at 172.31.32.97:6627
Exception in thread "main" org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
        at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
        at backtype.storm.command.list$_main.invoke(list.clj:22)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at backtype.storm.command.list.main(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
        ... 6 more
